### ISSUE TITLE
Question: What is the advantage of converting to SRT?

### ISSUE THREAD

**Issue by ZapRowsdower910** [hojel/SmiConvert.bundle#1]
Hi, wasn't sure the best way to ask this question so sorry if theres a better way.

I know very little about subtitle files in general and I was curious what the advantage of converting SMI files to SRT would be. I recently started pulling a new language for a friend and found that the files it downloads tend to be SMI files instead of the SRT's I'm used to seeing.  My assumption is its related to video player compatibility but Plex seems to support both formats. Any insight here would be appreciated.

**Comment by sinpie** [comment]
Hi, Plex media player on Android does not support SMI format subtitle files. But most Koreans use the format.
So, this is a PLEX media server agent code to automatically convert SMI to SRT when the media is added.

Usually, most media players on PC or Android support SMI format, so there shouldn't be an issue.
